version: '3.8'

services:
 db:
  build:
   context: ./docker/database
  container_name: mysql_
  ports:
  - 3306:3306
  networks:
   - default

 api:
  build:
   context: .
  container_name: api_
  depends_on:
   - "db"
  ports:
  - 8081:8081
  networks:
   - default

networks:
 my-network:
  driver: bridge
  external: true
  